version: "3.8"

services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    restart: unless-stopped
    environment:
      API_URL: "https://cobalt-api.up.railway.app/"
      CORS_WILDCARD: "1"

  cobalt-web:
    image: ghcr.io/spotdemo4/cobalt-web:latest
    restart: unless-stopped
    environment:
      WEB_DEFAULT_API: "https://cobalt-api.up.railway.app/"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cobalt-api
      - cobalt-web
